### ISSUE TITLE
Doesn't support Asp.Net Core 1.1 projects

### ISSUE THREAD

**Issue by craigktreasure** [originalmoose/Typescript.Definitions.Tools#3]
This tool looks fantastic and exactly what I've been looking for; however, I'm having a tough time figuring out why it isn't working for me. I've got a simple Asp.Net Core 1.1 app, i've added the bits noted in your Installation instructions, but when I run `dotnet tsd`, it ensures the app is built and that seems to be it. No errors. It seems as though the ConfigureDefinitions method on my Startup class isn't getting called at all. Any ideas?

**Comment by craigktreasure** [comment]
After cloning your repo and stepping through, it seems that your tool throws an exception when calling the Invoke method and when trying to create an instance of my Startup class:
`"Unable to resolve service for type 'Microsoft.AspNetCore.Hosting.IHostingEnvironment' while attempting to activate 'MyApp.Startup'."`

**Comment by originalmoose** [comment]
Honestly I should have released this project as a preview release just like the other dotnet tools. The toolchain is still under development and with there now being two build systems (VS2017 - msbuild, VS2015 - project.json) I haven't had the time to make the updates necessary to make this project work across all the current options.

I believe I attempted to get a 1.1 release working and was able to do so but only for VS2015 and the project.json layout. I'll double check and if it works Ill push another release.

**Comment by craigktreasure** [comment]
I appreciate it. I think you have the right idea.

**Comment by stephtr** [comment]
What changes where necessary for running it on 1.1 with project.json?

**Comment by originalmoose** [comment]
Unfortunately I still haven't been able to get this to work. I attempted updating all packages to the latest and tried a few things I thought might be the issue (removed some packages, etc) but I still get some errors when trying to use it in a test 1.1 project. The error's refer to an incorrect version of an AspNetCore lib. 

I'm going to have to take a look at some other examples to see what they are doing and perhaps get a clue as to what I am doing incorrectly. I haven't really been able to find any documentation on these type of tools projects and how to exactly get them setup properly. 

I'll happily accept pull requests if anyone is able to figure this out. With work where it's at right now I probably won't be able to spend any real time on this problem for a while.

**Comment by stephtr** [comment]
I don't get any errors after updating the packages. However I still get the "Unable to resolve service..." exception. If I replace the `assembly` in Program.cs's Main by `AssemblyLoadContext.Default.LoadFromAssemblyPath('...')` it works. Therefore it seems like the error is hiding within `ProjectContextFactory`.

**Comment by originalmoose** [comment]
> I don't get any errors after updating the packages. However I still get the "Unable to resolve service..." exception.

Yep that's what I was getting as well.

> If I replace the assembly in Program.cs's Main by AssemblyLoadContext.Default.LoadFromAssemblyPath('...') it works. Therefore it seems like the error is hiding within ProjectContextFactory.

Thanks! I took a quick look and I think I found what I need to change to get it working. I'll give it a shot during my lunch break and see how it goes. With any luck I'll be able to publish a 1.1 preview release this afternoon.

**Comment by originalmoose** [comment]
@stephtr Since you have the project pulled down and running with `AssemblyLoadContext.Default.LoadFromAssemblyPath('...')` you could give the change a try yourself. In ProjectContextFactory.cs take a look at line 28. I believe the problem is after updating the packages you need to also update `FrameworkConstants.CommonFrameworks.NetCoreApp10` to match

**Comment by originalmoose** [comment]
accidentally clicked close

**Comment by stephtr** [comment]
I actually did try that, but it didn't work.

**Comment by originalmoose** [comment]
So I thought I'd give it a try real quick this morning and when I switched to using `AssemblyLoadContext.Default.LoadFromAssemblyPath` I get the following error.

`Could not load file or assembly 'Microsoft.Extensions.Configuration, Version=1.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.`

When I use the existing assembly I get the following error.

`Unable to resolve service for type 'Microsoft.AspNetCore.Hosting.IHostingEnvironment' while attempting to activate 'TypescriptToolsTestingProject.Startup'.`

**Comment by stephtr** [comment]
It works for projects with no additional dependencies.
It seems like the ```IHostingEnvironment``` in this project is different than the one loaded using the LoadContext of the destination project: ```typeof(IHostingEnvironment).IsAssignableFrom(typeof(HostingEnvironment));``` returns true, but false, if I take the HostingEnvironment Type from the ```Microsoft.AspNetCore.Hosting``` assembly loaded using the destination project's LoadContext.

Maybe it is better to focus on supporting csproj.

**Comment by originalmoose** [comment]
> It seems like the IHostingEnvironment in this project is different than the one loaded using the LoadContext of the destination project: typeof(IHostingEnvironment).IsAssignableFrom(typeof(HostingEnvironment)); returns true, but false, if I take the HostingEnvironment Type from the Microsoft.AspNetCore.Hosting assembly loaded using the destination project's LoadContext.

This is the conclusion I came to as well. One thought I had was that in order to get it to work you need a separate library project for any code that has a dependency (Microsoft.AspNetCore.Hosting for example). If you look at EFCore tools, the tools project doesn't actually do anything, all it does is load the code to run from `Microsoft.EntityFrameworkCore.Design` which would be available in the destination project through the efcore dependency.

> Maybe it is better to focus on supporting csproj.

I think this is what I am going to do if splitting the project out into two packages doesn't work.

**Comment by originalmoose** [comment]
Since the issue is being caused by the IHostingEnvironment of the startup constructor I decided why not require the definitions in a separate class. The tool doesn't really need access to the Configuration object anyways. I gave it a quick try and it worked with the test project I used. I'll push out a release shortly and update the readme with what needs changed.

**Comment by originalmoose** [comment]
Version 1.1.0-preview1-final has been published. You can use this in net core 1.1 projects. I have updated the readme to show how to get it setup. If you want to see the code changes they are under the 1.1.0-preview1 branch.

**Comment by stephtr** [comment]
That approach looks clean.
However by using ```AssemblyLoadContext.Default.LoadFromAssemblyPath(startupProject.Assembly.Location);``` it now doesn't work using shared projects, because that way startupProject's dependencies doesn't get loaded.
Using the old way ```typeof(ITypedef).IsAssignableFrom(t.AsType())``` returns false, like with the IHostingEnvironment.

**Comment by stephtr** [comment]
And if I solve those errors, I still get ```Object of type 'Typescript.Definitions.Tools.TypescriptDefinitionBuilder' cannot be converted to type 'Typescript.Definitions.Tools.IDefinitionBuilder'```
I guess I will wait for the official release of 1.0.0 and then try to migrate it to csproj.

**Comment by originalmoose** [comment]
> That approach looks clean.
However by using AssemblyLoadContext.Default.LoadFromAssemblyPath(startupProject.Assembly.Location); it now doesn't work using shared projects, because that way startupProject's dependencies doesn't get loaded.
Using the old way typeof(ITypedef).IsAssignableFrom(t.AsType()) returns false, like with the IHostingEnvironment.

I didn't realize I kept the AssemblyLoadContext line in there. I think I know what I can do to fix it but I probably won't have time until this weekend. I believe all I have to do is pull ITypedef and IDefinitionBuilder into their own package (I'll probably call it Typescript.Definitions.Abstractions). I believe this is the missing piece of the puzzle. That way the target project would pull in the interfaces in it's dependencies and the tool separately in the tools. Not sure if it will work but it's worth a shot.

**Comment by originalmoose** [comment]
At this point I think I have decided to abandon this project.

I recently found [Typewriter](https://frhagn.github.io/Typewriter/) and it has more than suited my needs. It uses template's and special syntax to allow you to create truly custom definitions (or even full ts files) from your cs files.

If anyone would like to fork and take over the project feel free, but seeing as how it was mainly a clone of TypeLite I don't think that's really necessary.

**Comment by stephtr** [comment]
Thank you for your work!
Unfortunately Typewriter is limited to Windows and VS, but for other platforms there are alternatives, like [typescript-cs-poco](https://www.npmjs.com/package/typescript-cs-poco). In the long term I hope that TypeLite eventually catches up with this project by supporting dotnet core.
